-- U5 — Guest list model.
-- Plan: docs/plans/2026-08-15-001-feat-unified-purchase-module-plan.md
--
-- A guest list is a list attached to an event: a list name, a list contact (name, email,
-- phone), and guests who each hold a registration-less ticket. There is no entries table —
-- a guest on a list IS a ticket (KD10). This is the whole schema change: one new table plus
-- one nullable column on `tickets`.
--
-- CAPACITY (KTD4): the seat count (the `seats_used` RPC, see lib/events/seat-usage.ts) sums
-- `event_registrations.quantity` and never reads `tickets` at all. A guest-list ticket has
-- no registration and no registration_items row, so it is structurally invisible to that
-- read — not filtered out, just never in the tables the count looks at. Do NOT add a
-- `WHERE NOT ...` predicate anywhere to achieve this; the absence of a registration is what
-- makes the exclusion permanent.
--
-- KTD5: this list starts EMPTY. The three historical comp lists (is_guest_list on
-- event_registrations, is_comp on tickets) are not migrated into it — they stay exactly as
-- they are until U7 retires their read paths.
--
-- KTD10: `tickets.registration_id` is already nullable in production (no CHECK, no
-- NOT NULL) — this migration mints the first rows that actually use that nullability.
-- A guest-list ticket is created with slot_status = 'issued' and a name (email optional),
-- which satisfies tickets_contact_present's first disjunct
-- (`slot_status = any(array['unclaimed','issued'])`, see
-- supabase/migrations/20260721140100_tighten_contact_present.sql) with no dependency on
-- is_comp. Once the door checks the guest in, checked_in_at satisfies the fourth disjunct
-- for the rest of the row's life. No constraint change is needed here.
--
-- RLS: event_guest_lists enables row-level security with NO anon/authenticated policy —
-- reachable only through the service-role admin client behind the admin route (mirrors
-- event_registration_topups / event_ticket_type_conversions / comp_guest_batches).
--
-- SHARED DEV/PROD DATABASE: this migration applies to production immediately. It is
-- purely additive (one new table, one new nullable FK column, two indexes) — nothing
-- existing changes shape or value, so there is no backfill and nothing destructive.
--
-- TYPES: types/database.ts is NOT regenerated by this migration. U5/U6 declare local row
-- types until U8 regenerates once, after this migration has applied. When it does,
-- RE-APPEND the hand-written MemberStatus / PaymentCaptureStatus aliases — the generator
-- drops them every time.

create table if not exists public.event_guest_lists (
  id             uuid primary key default gen_random_uuid(),
  event_id       uuid not null references public.events(id) on delete cascade,
  list_name      text not null,
  contact_name   text not null,
  contact_email  text,
  contact_phone  text,
  created_at     timestamptz not null default now()
);

-- Service-role-only in fact, not just by convention: RLS on, no policies at all.
alter table public.event_guest_lists enable row level security;

create index if not exists event_guest_lists_event_idx
  on public.event_guest_lists (event_id);

-- The only schema change to `tickets`: nullable, so every existing row is unaffected.
-- No `on delete cascade` — deleting a list goes through the app (lib/events/guest-lists.ts),
-- which deletes the list's never-checked-in tickets first and refuses the whole delete if
-- any ticket on the list has checked in; the default FK action (restrict) is a backstop
-- against a future write path that tries to delete a list out from under live tickets.
alter table public.tickets
  add column if not exists guest_list_id uuid references public.event_guest_lists(id);

create index if not exists tickets_guest_list_idx
  on public.tickets (guest_list_id)
  where guest_list_id is not null;
